# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\rLogoutRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"0\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2]\n\x0b\x41uthService\x12%\n\x05Login\x12\r.LoginRequest\x1a\r.AuthResponse\x12\'\n\x06Logout\x12\x0e.LogoutRequest\x1a\r.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=22
  _globals['_LOGINREQUEST']._serialized_end=72
  _globals['_LOGOUTREQUEST']._serialized_start=74
  _globals['_LOGOUTREQUEST']._serialized_end=109
  _globals['_AUTHRESPONSE']._serialized_start=111
  _globals['_AUTHRESPONSE']._serialized_end=159
  _globals['_AUTHSERVICE']._serialized_start=161
  _globals['_AUTHSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
