# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x04\x66ile\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0eGoodbyeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fGoodbyeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"!\n\x0cTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"C\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\"&\n\x11\x46ilesListResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t2\xa3\x02\n\x0b\x46ileService\x12\x35\n\x08SayHello\x12\x12.file.HelloRequest\x1a\x13.file.HelloResponse\"\x00\x12;\n\nSayGoodbye\x12\x14.file.GoodbyeRequest\x1a\x15.file.GoodbyeResponse\"\x00\x12\x32\n\rGetServerTime\x12\x0b.file.Empty\x1a\x12.file.TimeResponse\"\x00\x12\x34\n\tWriteFile\x12\x11.file.FileRequest\x1a\x12.file.FileResponse\"\x00\x12\x36\n\x0cGetFilesList\x12\x0b.file.Empty\x1a\x17.file.FilesListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=56
  _globals['_HELLORESPONSE']._serialized_start=58
  _globals['_HELLORESPONSE']._serialized_end=90
  _globals['_GOODBYEREQUEST']._serialized_start=92
  _globals['_GOODBYEREQUEST']._serialized_end=122
  _globals['_GOODBYERESPONSE']._serialized_start=124
  _globals['_GOODBYERESPONSE']._serialized_end=158
  _globals['_EMPTY']._serialized_start=160
  _globals['_EMPTY']._serialized_end=167
  _globals['_TIMERESPONSE']._serialized_start=169
  _globals['_TIMERESPONSE']._serialized_end=202
  _globals['_FILEREQUEST']._serialized_start=204
  _globals['_FILEREQUEST']._serialized_end=252
  _globals['_FILERESPONSE']._serialized_start=254
  _globals['_FILERESPONSE']._serialized_end=321
  _globals['_FILESLISTRESPONSE']._serialized_start=323
  _globals['_FILESLISTRESPONSE']._serialized_end=361
  _globals['_FILESERVICE']._serialized_start=364
  _globals['_FILESERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
