# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'file_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\x12\x04\x66ile\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"!\n\x0cTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"h\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x11\n\tfile_size\x18\x04 \x01(\x03\x12\x10\n\x08md5_hash\x18\x05 \x01(\t\"H\n\x13\x46ileContentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x0f\n\x07message\x18\x03 \x01(\t\"e\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x13\n\x0bmodified_at\x18\x04 \x01(\t\x12\x10\n\x08md5_hash\x18\x05 \x01(\t\"2\n\x11\x46ilesListResponse\x12\x1d\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0e.file.FileInfo2\xd9\x02\n\x0b\x46ileService\x12\x35\n\x08SayHello\x12\x12.file.HelloRequest\x1a\x13.file.HelloResponse\"\x00\x12\x32\n\rGetServerTime\x12\x0b.file.Empty\x1a\x12.file.TimeResponse\"\x00\x12\x34\n\tWriteFile\x12\x11.file.FileRequest\x1a\x12.file.FileResponse\"\x00\x12:\n\x08ReadFile\x12\x11.file.FileRequest\x1a\x19.file.FileContentResponse\"\x00\x12\x35\n\nDeleteFile\x12\x11.file.FileRequest\x1a\x12.file.FileResponse\"\x00\x12\x36\n\x0cGetFilesList\x12\x0b.file.Empty\x1a\x17.file.FilesListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=56
  _globals['_HELLORESPONSE']._serialized_start=58
  _globals['_HELLORESPONSE']._serialized_end=90
  _globals['_EMPTY']._serialized_start=92
  _globals['_EMPTY']._serialized_end=99
  _globals['_TIMERESPONSE']._serialized_start=101
  _globals['_TIMERESPONSE']._serialized_end=134
  _globals['_FILEREQUEST']._serialized_start=136
  _globals['_FILEREQUEST']._serialized_end=184
  _globals['_FILERESPONSE']._serialized_start=186
  _globals['_FILERESPONSE']._serialized_end=290
  _globals['_FILECONTENTRESPONSE']._serialized_start=292
  _globals['_FILECONTENTRESPONSE']._serialized_end=364
  _globals['_FILEINFO']._serialized_start=366
  _globals['_FILEINFO']._serialized_end=467
  _globals['_FILESLISTRESPONSE']._serialized_start=469
  _globals['_FILESLISTRESPONSE']._serialized_end=519
  _globals['_FILESERVICE']._serialized_start=522
  _globals['_FILESERVICE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
