# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"!\n\x0cTimeResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"0\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"C\n\x0c\x46ileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\"&\n\x11\x46ilesListResponse\x12\x11\n\tfilenames\x18\x01 \x03(\t2\xfe\x01\n\x0b\x46ileService\x12;\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\"\x00\x12\x38\n\rGetServerTime\x12\x0e.example.Empty\x1a\x15.example.TimeResponse\"\x00\x12:\n\tWriteFile\x12\x14.example.FileRequest\x1a\x15.example.FileResponse\"\x00\x12<\n\x0cGetFilesList\x12\x0e.example.Empty\x1a\x1a.example.FilesListResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLORESPONSE']._serialized_start=56
  _globals['_HELLORESPONSE']._serialized_end=88
  _globals['_EMPTY']._serialized_start=90
  _globals['_EMPTY']._serialized_end=97
  _globals['_TIMERESPONSE']._serialized_start=99
  _globals['_TIMERESPONSE']._serialized_end=132
  _globals['_FILEREQUEST']._serialized_start=134
  _globals['_FILEREQUEST']._serialized_end=182
  _globals['_FILERESPONSE']._serialized_start=184
  _globals['_FILERESPONSE']._serialized_end=251
  _globals['_FILESLISTRESPONSE']._serialized_start=253
  _globals['_FILESLISTRESPONSE']._serialized_end=291
  _globals['_FILESERVICE']._serialized_start=294
  _globals['_FILESERVICE']._serialized_end=548
# @@protoc_insertion_point(module_scope)
